vagrant-vm:
  docker:
    enabled: true
    # entries:
    #   - _id: "0"
    #     host: registry.gitlab.com
    #     force: false
    #     username: <your username>
    #     password: <your password>

  # to use VIRTUAL_HOST in any docker container
  proxy:
    enabled: false
    name: nginx-proxy
    image: jwilder/nginx-proxy:alpine
    restart_policy: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/certs:/etc/nginx/certs
    port:
      - 80:80
      - 443:443

  # to use inside the VM
  enviroment:
    enabled: false
    items:
      - _id: "0"
        prefix: 
        subfix: 
        items:
          KEY: "VALUE" # PREFIX_KEY_SUBIFX=VALUE

  template:
    enabled: false
    items:
      - _id: "0"
        lookup: # default at extensions
        filename: "vagrant-vm/templates/index.html.tpl" # your config file, index.html.tpl will be parsed to index.html
        target: # default at VM $HOME:/home/vagrant
        values:
          name: vagrant # key/value pair
